import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const overusedGrotesk = localFont({
  src: [
    {
      path: '../assets/fonts/OverusedGrotesk-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-overused-grotesk'
});

const playfairDisplay = localFont({
  src: [
    {
      path: '../assets/fonts/PlayfairDisplay-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/PlayfairDisplay-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf',
      weight: '800',
      style: 'italic',
    },
    {
      path: '../assets/fonts/PlayfairDisplay-BlackItalic.ttf',
      weight: '900',
      style: 'italic',
    },
  ],
  variable: '--font-playfair-display'
});

export const metadata: Metadata = {
  title: "StartUp",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body className={`${overusedGrotesk.variable} ${playfairDisplay.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}