import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const overusedGrotesk = localFont({
  src: [
    {
      path: '../assets/fonts/OverusedGrotesk-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../assets/fonts/OverusedGrotesk-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-overused-grotesk'
});

export const metadata: Metadata = {
  title: "StartUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${overusedGrotesk.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}